name: forge
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask
  - datashader
  - fsspec
  - gdal
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - jupyter-panel-proxy
  - jupyterlab>=3
  - nbgitpuller
  - panel
  - param
  - progressbar2
  - qgis
  - rasterio
  - rioxarray
  - pip
  - pip:
    - git+https://github.com/fastice/gimpfunc.git@HEAD
