name: forge
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh
  - dask
  - datashader
  - fsspec
  - gdal
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - intake
  - intake-stac
  - intake-xarray
  - jupyter-panel-proxy
  - jupyterlab>=3
  - nbgitpuller
  - panel
  - param
  - progressbar2
  - pyviz_comms
  - qgis
  - rasterio
  - rioxarray
  - sat-search
  - sat-stac
  - xarray
